name: todo_app
description: ToDoApp.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
